apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: k8s-workshop-secret 
spec:
  backendType: vault 
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - key: io/data/rewardops/jx/staging/k8s-workshop/k8s-workshop-secret 
      name: password
      property: password
    - key: io/data/rewardops/jx/staging/k8s-workshop/k8s-workshop-secret 
      name: username 
      property: username
    - key: io/data/rewardops/jx/staging/k8s-workshop/k8s-workshop-secret 
      name: APP_CONFIG_SECRET 
      property: APP_CONFIG_SECRET
    - key: io/data/rewardops/testing-api
      name: testing-settings.local.yml
      property: settings.local.yml
