---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          imagePullPolicy: Never
          image: rewardops/k8s-workshop:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/k8s-workshop-configmap
          envFrom:
            - secretRef:
                name: k8s-workshop-secret
      volumes:
        - name: config-volume
          configMap:
            name: k8s-workshop-configmap
